(defpackage #:lisp-tracer
  (:use #:cl
        #:iterate
        #:arrows)
  (:export
   #:add
   #:ambient
   #:black
   #:blue
   #:canvas
   #:canvas-to-ppm
   #:color
   #:cross
   #:diffuse
   #:direction
   #:div
   #:dot
   #:epsilon
   #:equal?
   #:green
   #:height
   #:hit
   #:identity-matrix
   #:intensity
   #:intersect
   #:intersection
   #:intersections
   #:inverse
   #:lighting
   #:magnitude
   #:make-canvas
   #:make-color
   #:make-intersection
   #:make-material
   #:make-matrix
   #:create-matrix
   #:make-point
   #:make-ray
   #:make-sphere
   #:create-tuple
   #:make-vec
   #:mapcolor
   #:mapnumber
   #:maptuple
   #:material
   #:material-color
   #:matrix
   #:mult
   #:neg
   #:normal-at
   #:normalize
   #:object
   #:origin
   #:pixel-at
   #:point
   #:point-light
   #:point?
   #:pos
   #:posit
   #:ray
   #:red
   #:reflect
   #:rotation-x
   #:rotation-y
   #:rotation-z
   #:scaling
   #:set-transform
   #:shearing
   #:shininess
   #:specular
   #:sphere
   #:sphere-material
   #:sub
   #:to-pixel
   #:transform
   #:transform-matrix
   #:transform-object
   #:translation
   #:transpose
   #:tt
   #:tuple
   #:tuple-to-list
   #:vec
   #:vec?
   #:width
   #:write-pixel
   #:tuple-x
   #:tuple-y
   #:tuple-z
   #:tuple-w
   #:zerovec
   #:matrix-m00
   #:matrix-m01
   #:matrix-m02
   #:matrix-m03
   #:matrix-m10
   #:matrix-m11
   #:matrix-m12
   #:matrix-m13
   #:matrix-m20
   #:matrix-m21
   #:matrix-m22
   #:matrix-m23
   #:matrix-m30
   #:matrix-m31
   #:matrix-m32
   #:matrix-m33
   ))
