(defpackage #:lisp-tracer
  (:use #:cl
        #:iterate)
  (:export
   #:add
   #:canvas
   #:canvas-height
   #:canvas-to-ppm
   #:canvas-width
   #:color
   #:color-at
   #:color-blue
   #:color-green
   #:color-red
   #:computations-eyev
   #:computations-inside
   #:computations-normalv
   #:computations-object
   #:computations-point
   #:computations-tt
   #:create-canvas
   #:create-matrix
   #:cross
   #:default-world
   #:div
   #:dot
   #:epsilon
   #:equal?
   #:hit
   #:identity-matrix
   #:intersect
   #:intersection
   #:intersections
   #:intersect-world
   #:inverse
   #:lighting
   #:light-intensity
   #:light-position
   #:magnitude
   #:make-canvas
   #:make-color
   #:make-intersection
   #:make-material
   #:make-matrix
   #:make-point
   #:make-ray
   #:make-sphere
   #:make-tuple
   #:make-vec
   #:make-world
   #:material
   #:material-ambient
   #:material-col
   #:material-diffuse
   #:material-shininess
   #:material-specular
   #:matrix
   #:matrix-m00
   #:matrix-m01
   #:matrix-m02
   #:matrix-m03
   #:matrix-m10
   #:matrix-m11
   #:matrix-m12
   #:matrix-m13
   #:matrix-m20
   #:matrix-m21
   #:matrix-m22
   #:matrix-m23
   #:matrix-m30
   #:matrix-m31
   #:matrix-m32
   #:matrix-m33
   #:mult
   #:neg
   #:normal-at
   #:normalize
   #:pixel-at
   #:point
   #:point?
   #:point-light
   #:pos
   #:prepare-computations
   #:ray
   #:ray-direction
   #:ray-origin
   #:reflect
   #:rotation-x
   #:rotation-y
   #:rotation-z
   #:rt-intersection-object
   #:rt-intersection-tt
   #:scaling
   #:set-transform
   #:shade-hit
   #:shearing
   #:sphere
   #:sphere-material
   #:sphere-matrix
   #:sub
   #:transform
   #:transform-object
   #:translation
   #:transpose
   #:tuple
   #:tuple-w
   #:tuple-x
   #:tuple-y
   #:tuple-z
   #:vec
   #:vec?
   #:view-transform
   #:world-light
   #:world-objects
   #:write-pixel
   #:zerovec
   ))
